const USERS=[
  {email:'1',pass:'1',role:'banco',name:'Banco LAFISE - Analista de Crédito'},
  {email:'2',pass:'2',role:'coop',name:'Coop. Cafetalera Marcala'},
  {email:'3',pass:'3',role:'imf',name:'ODEF Financiera - Oficial de Cartera'},
  {email:'banco@lafise.hn',pass:'banco2024',role:'banco',name:'Banco LAFISE - Analista de Crédito'},
  {email:'gestor@cofemarcala.hn',pass:'coop2024',role:'coop',name:'Coop. Cafetalera Marcala'},
  {email:'oficial@odef.hn',pass:'imf2024',role:'imf',name:'ODEF Financiera - Oficial de Cartera'},
];

// ── Metrics and tools ──────────────────────────────────────────────────────
const precioFundamentales=100;

const ESG=[
  {id:'e1',label:'aCLIMAtar',cost:50},
  {id:'e2',label:'Whisp - Open Foris',cost:50},
  {id:'e4',label:'Croppie',cost:50},
];

const ACLIMATAR_CONFIG = {
  n:   'aCLIMAtar',
  src: 'Alianza Bioversity Internacional y CIAT, Producers Direct, Fundación Mundial del Cacao (WCF), Rikolto, Fundación Hanns R. Neumann Stiftung.',
  aptitudClimActualClass: {
    low:'low',medium:'medium',high:'high',uncertain:'uncertain',limitations:'limitations',unsuitable:'unsuitable',unknown:'unknown'},
  aptitudClimActualLabel: {
    low:'Déficit hídrico bajo',medium:'Déficit hídrico intermedio',high:'Déficit hídrico alto',uncertain:'Aptitud incierta',limitations:'Con limitaciones',unsuitable:'No idóneo',unknown:'Sin información'},
  aptitudClimActualInterp: {
    low: 'La zona presenta un déficit hídrico bajo en época seca, lo que indica condiciones generalmente favorables para el cultivo. La duración y severidad del estrés hídrico son limitadas, aunque pueden existir variaciones locales.',
    medium: 'La época seca en esta zona tiene un déficit hídrico intermedio, tiene una duración de 4,3 meses y 78mm en promedio de lluvia trimestral. El trimestre más seco en esta zona tiene una temperatura promedio aproximada de 19°C. Estos valores son un promedio de toda la zona, pero las condiciones varían según la ubicación.',
    high: 'La zona presenta un déficit hídrico alto en época seca, lo que sugiere condiciones restrictivas para el cultivo. Es probable que se requieran medidas de adaptación para sostener la producción.',
    uncertain: 'Las condiciones de déficit hídrico no pueden ser clasificadas con precisión debido a la variabilidad o falta de datos suficientes en la zona.',
    limitations: 'Existen limitaciones importantes en la disponibilidad de información climática para esta zona, lo que restringe la precisión de la clasificación.',
    unsuitable: 'Las condiciones de déficit hídrico indican que la zona no es adecuada para el cultivo bajo los parámetros actuales.',
    unknown: ''},
  aptitudClimFuturaClass: {
    low:'low',medium:'medium',high:'high',uncertain:'uncertain',limitations:'limitations',unsuitable:'unsuitable',unknown:'unknown'},
  aptitudClimFuturaLabel: {
    low:'Déficit hídrico bajo',medium:'Déficit hídrico intermedio',high:'Déficit hídrico alto',uncertain:'Aptitud incierta',limitations:'Con limitaciones',unsuitable:'No idóneo',unknown:'Sin información'},
  aptitudClimFuturaInterp: {
    low: 'Las proyecciones climáticas sugieren que la zona mantendrá condiciones relativamente favorables para el cultivo en los próximos 30 años, con cambios moderados en el balance hídrico.',
    medium: 'Las proyecciones indican una transición hacia condiciones intermedias, donde el cultivo seguirá siendo viable pero con mayor exposición a estrés climático.',
    high: 'Las proyecciones muestran un aumento significativo del estrés climático, lo que podría reducir la idoneidad de la zona para el cultivo en el mediano plazo.',
    uncertain: 'Estas zonas son aptas para el cultivo, pero la información climática no nos permite clasificarlas claramente en una de las zonas agroclimáticas, porque están entre dos zonas y tienen características de ambas.',
    limitations: 'Las limitaciones en los modelos o datos disponibles reducen la confiabilidad de la proyección climática para esta zona.',
    unsuitable: 'Las proyecciones indican condiciones desfavorables persistentes para el cultivo en el horizonte de 30 años.',
    unknown: ''},
  gradienteClimClass: {
    low:'low',medium:'medium',high:'high',unsuitable:'unsuitable',unknown:'unknown'},
  gradienteClimLabel: {
    low:'Adaptación incremental',medium:'Adaptación sistématica',high:'Adaptación transformacional',unsuitable:'No idóneo',unknown:'Sin información'},
  gradienteClimInterp: {
    low: 'Donde es más probable que el clima siga siendo adecuado y la adaptación se logrará mediante un cambio de prácticas y estrategias y facilitadores idealmente mejorados. Los patrones alterados de plagas y enfermedades, la lluvia incierta, la sequía y el calor pueden afectar el cultivo, pero la producción de cacao seguirá siendo factible.',
    medium: 'El cambio climático proyectado requiere adaptación sistemática, con ajustes más estructurales en manejo agronómico y estrategias productivas.',
    high: 'El cambio climático proyectado implica una adaptación transformacional, donde podrían requerirse cambios significativos en el sistema productivo o incluso en la viabilidad del cultivo.',
    unsuitable: 'El nivel de cambio proyectado sugiere condiciones no aptas para la continuidad del cultivo bajo el sistema actual.',
    unknown: ''},
  calorClass: {
    low:'low',medium:'medium',high:'high',unsuitable:'unsuitable',unknown:'unknown'},
  calorLabel: {
    low:'Riesgo bajo',medium:'Riesgo medio',high:'Riesgo alto',unsuitable:'No idóneo',unknown:'Sin información'},
  calorInterp: {
    low: 'La exposición a temperaturas elevadas es baja en comparación con zonas cafetaleras típicas, aunque pueden presentarse episodios puntuales de calor.',
    medium: 'La exposición a temperaturas elevadas es moderada y puede generar estrés térmico ocasional en el cultivo durante ciertas épocas del año.',
    high: 'Es probable que experimente temperaturas inusuales a las que conocen actualmente áreas cafetaleras.',
    unsuitable: 'Las condiciones térmicas son severas y no adecuadas para el cultivo bajo los parámetros actuales.',
    unknown: ''},
  sequiaClass: {
    low:'low',medium:'medium',high:'high',unsuitable:'unsuitable',unknown:'unknown'},
  sequiaLabel: {
    low:'Riesgo bajo',medium:'Riesgo medio',high:'Riesgo alto',unsuitable:'No idóneo',unknown:'Sin información'},
  sequiaInterp: {
    low: 'La disponibilidad hídrica en época seca es relativamente estable, lo que reduce el riesgo de estrés hídrico para el cultivo.',
    medium: 'La época seca presenta restricciones hídricas moderadas que pueden afectar el rendimiento si no se implementan prácticas de manejo adecuadas.',
    high: 'La época seca presenta fuertes restricciones hídricas, lo que aumenta significativamente el riesgo de afectación del cultivo.',
    unsuitable: 'La zona de su ubicación se clasifica como No idónea. La época seca presenta limitaciones para la caficultura.',
    unknown: ''}
  };

const WHISP_CONFIG = {
  n:   'Whisp - Open Foris',
  src: 'Organización de las Naciones Unidas para la Alimentación y la Agricultura - 2025 OpenForis.',
  riskClass: {
    low:'low',high:'high',uncertain:'uncertain',unknown:'unknown'},
  riskLabel: {
    low:'Riesgo bajo',high:'Riesgo Alto',uncertain:'Se requiere más información',unknown:'Sin información'},
  riskInterp: {
    low:      'La finca no presenta superposición con áreas de bosque cartografiado activo, o sus coincidencias corresponden a perturbaciones anteriores a finales de 2020. Sin indicios de deforestación reciente.',
    high:     'La finca se encuentra dentro de un área de bosque cartografiado y registra una perturbación detectada después de 2020. Se recomienda verificación adicional antes del desembolso.',
    uncertain: 'La finca coincide con un área de bosque cartografiado sin perturbaciones registradas antes ni después de 2020, y sin solapamiento con actividades económicas. Se requiere investigación más detallada para determinar cumplimiento EUDR.',
  }
};

const CROPPIE_CONFIG = {
  n:   'Croppie',
  src: 'Alianza Bioversity Internacional y CIAT, Producers Direct, Tecnicafé.',
};


// ── Credits list: demo ──────────────────────────────────────────────────────
const LOANS_BANCO_TEST=[
  {id:'tb1',tipo:'banco',testValue:'yes',fechaDesembolso:'2026-06-01',name:'Exportadora El Paraíso',region:'El Paraíso, Honduras',
    acopio:'1,200,000',productores:'220,000',nProd:10,paqueteFlexible: true,
    destinos:'Insumos, Cosecha, Renovación',areaProd:'20.7',volumenTotal:'511',
    plazoAcopio:'6',anios:12,volExport:'1,840',contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'800',mercados:'Alemania, Países Bajos',
    prod:[
      {cod:'HN-tb1-001',nombre:'Martínez Flores, J.',monto:'L. 18,000',plazo:'5 meses',destino:'Insumos',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'2.4 mz', geo:'14.21°N 86.83°W',carnet:'IHCAFE-2021-0041',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'42 qq / 3 ciclos',histIngresos:'1000 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'5000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim: 'high', calor: 'unknown', sequia: 'unsuitable', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'22', production:'110', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-002',nombre:'López Aguilar, R.',monto:'L. 22,000',plazo:'6 meses',destino:'Cosecha',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'1.3 mz', geo:'14.18°N 86.91°W',carnet:'IHCAFE-2020-0052',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'55 qq / 4 ciclos',histIngresos:'2000 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim: 'high', calor: 'unknown', sequia: 'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'high', estimationDate:'2026-05-15'},
        {id:'e4', yield:'22', production:'110', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-003',nombre:'García Hernández, M.',monto:'L. 20,000',plazo:'6 meses',destino:'Insumos',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'2.1 mz', geo:'14.20°N 86.85°W',carnet:'IHCAFE-2021-0043',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'48 qq / 3 ciclos',histIngresos:'1500 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'3000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'24', production:'115', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-004',nombre:'Ramírez Cruz, E.',monto:'L. 25,000',plazo:'7 meses',destino:'Cosecha',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'1.8 mz', geo:'14.19°N 86.87°W',carnet:'IHCAFE-2019-0064',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'52 qq / 4 ciclos',histIngresos:'2200 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'high', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'high', estimationDate:'2026-05-15'},
        {id:'e4', yield:'20', production:'98', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-005',nombre:'Castillo Mejía, P.',monto:'L. 17,000',plazo:'5 meses',destino:'Insumos',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'1.5 mz', geo:'14.22°N 86.88°W',carnet:'IHCAFE-2022-0070',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'38 qq / 2 ciclos',histIngresos:'1200 HNL / 2 ciclos',otherIncome:'Sí', amountOtherIncome:'2500 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'medium', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'25', production:'120', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-006',nombre:'Rodríguez Funes, C.',monto:'L. 28,000',plazo:'8 meses',destino:'Renovación',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'3.0 mz', geo:'14.23°N 86.84°W',carnet:'IHCAFE-2018-0082',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'68 qq / 5 ciclos',histIngresos:'3500 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'6000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'high', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'27', production:'145', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-007',nombre:'Morales Pineda, A.',monto:'L. 19,000',plazo:'5 meses',destino:'Insumos',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'1.2 mz', geo:'14.17°N 86.90°W',carnet:'IHCAFE-2021-0091',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'30 qq / 3 ciclos',histIngresos:'900 HNL / 3 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'unknown', sequia:'unsuitable', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'high', estimationDate:'2026-05-15'},
        {id:'e4', yield:'18', production:'85', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-008',nombre:'Santos Rivera, D.',monto:'L. 24,000',plazo:'6 meses',destino:'Cosecha',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'2.7 mz', geo:'14.24°N 86.86°W',carnet:'IHCAFE-2020-0105',variedad:'IHCAFE 90',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'60 qq / 4 ciclos',histIngresos:'2800 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'4500 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'low', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'26', production:'135', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-009',nombre:'Vásquez Romero, H.',monto:'L. 21,000',plazo:'6 meses',destino:'Insumos',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'1.9 mz', geo:'14.18°N 86.84°W',carnet:'IHCAFE-2019-0113',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'46 qq / 4 ciclos',histIngresos:'1800 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'medium', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'23', production:'112', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb1-010',nombre:'Pérez Mendoza, S.',monto:'L. 26,000',plazo:'7 meses',destino:'Renovación',aval:'A',
        department:'El Paraíso', municipality:'Danlí', aldea:'Las Marías', areaProd:'2.8 mz', geo:'14.21°N 86.89°W',carnet:'IHCAFE-2018-0124',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'72 qq / 5 ciclos',histIngresos:'4000 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'7000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'high', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'28', production:'155', estimationDate:'2026-05-15'},
      ]},
      ]},
  {id:'tb2',tipo:'banco',testValue:'yes',fechaDesembolso:'2026-06-02',name:'Beneficio Río Frío',region:'Santa Bárbara, Honduras',
    acopio:'2,400,000',productores:'254,000',nProd:12,paqueteFlexible:false,
    destinos:'Insumos, Cosecha, Renovación',areaProd:'24.9',volumenTotal:'602',
    plazoAcopio:'6',anios:12,volExport:'1,840',contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'950',mercados:'Alemania, Países Bajos',
    prod:[
      {cod:'HN-tb2-001',nombre:'Gómez Mejía, L.',monto:'L. 19,000',plazo:'6 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'El Porvenir', areaProd:'1.8 mz', geo:'14.93°N 88.28°W',carnet:'IHCAFE-2021-0201',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'40 qq / 3 ciclos',histIngresos:'1200 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'3000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua',
          practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'21', production:'100', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-002',nombre:'Hernández Ruiz, M.',monto:'L. 24,000',plazo:'7 meses',destino:'Cosecha',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'Los Laureles', areaProd:'2.2 mz', geo:'14.94°N 88.26°W',carnet:'IHCAFE-2020-0188',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'55 qq / 4 ciclos',histIngresos:'2000 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'high', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de árboles de sombra, Cosecha de agua',
          practicasRecomendadas:'Uso de biochar en vivero, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'23', production:'118', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-003',nombre:'Castro Aguilar, J.',monto:'L. 21,000',plazo:'6 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'San Juan', areaProd:'1.6 mz', geo:'14.92°N 88.29°W',carnet:'IHCAFE-2019-0172',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'38 qq / 3 ciclos',histIngresos:'1100 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'2500 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra',
          practicasRecomendadas:'Injerto, Renovación de cafetales, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'20', production:'95', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-004',nombre:'López Pineda, R.',monto:'L. 26,000',plazo:'8 meses',destino:'Renovación',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'El Cedral', areaProd:'2.5 mz', geo:'14.95°N 88.27°W',carnet:'IHCAFE-2018-0150',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'65 qq / 5 ciclos',histIngresos:'3200 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'6000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de cafetales, Cosecha de agua',
          practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'26', production:'140', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-005',nombre:'Mejía Santos, D.',monto:'L. 18,000',plazo:'5 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'La Esperanza', areaProd:'1.4 mz', geo:'14.91°N 88.30°W',carnet:'IHCAFE-2022-0210',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'35 qq / 2 ciclos',histIngresos:'900 HNL / 2 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'unknown', sequia:'unsuitable', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua',
          practicasRecomendadas:'Fertilización orgánica'},
        {id:'e2', risk:'high', estimationDate:'2026-05-15'},
        {id:'e4', yield:'18', production:'80', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-006',nombre:'Rivera Castro, P.',monto:'L. 23,000',plazo:'6 meses',destino:'Cosecha',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'El Roble', areaProd:'2.0 mz', geo:'14.96°N 88.25°W',carnet:'IHCAFE-2020-0199',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'50 qq / 4 ciclos',histIngresos:'2100 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'4000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de árboles de sombra',
          practicasRecomendadas:'Injerto, Conservación de suelos, Fertilización orgánica'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'22', production:'110', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-007',nombre:'Vásquez Flores, A.',monto:'L. 20,000',plazo:'6 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'El Paraíso Alto', areaProd:'1.7 mz', geo:'14.90°N 88.31°W',carnet:'IHCAFE-2019-0166',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'42 qq / 3 ciclos',histIngresos:'1300 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'2800 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Cosecha de agua',
          practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'21', production:'105', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-008',nombre:'Ordoñez Mendoza, C.',monto:'L. 27,000',plazo:'8 meses',destino:'Renovación',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'Las Flores', areaProd:'2.6 mz', geo:'14.97°N 88.24°W',carnet:'IHCAFE-2018-0142',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'70 qq / 5 ciclos',histIngresos:'3500 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'6500 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'high', gradienteClim:'high', calor:'medium', sequia:'high', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de cafetales, Cosecha de agua',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'28', production:'150', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-009',nombre:'Flores Reyes, J.',monto:'L. 22,000',plazo:'6 meses',destino:'Cosecha',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'El Carmen', areaProd:'2.1 mz', geo:'14.93°N 88.27°W',carnet:'IHCAFE-2020-0138',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'48 qq / 4 ciclos',histIngresos:'1800 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Conservación de suelos',
          practicasRecomendadas:'Injerto, Fertilización orgánica'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'24', production:'120', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-010',nombre:'Méndez Aguilar, S.',monto:'L. 25,000',plazo:'7 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'La Unión', areaProd:'2.3 mz', geo:'14.98°N 88.23°W',carnet:'IHCAFE-2017-0120',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'60 qq / 4 ciclos',histIngresos:'2500 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'5000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de árboles de sombra, Cosecha de agua',
          practicasRecomendadas:'Injerto, Conservación de suelos, Fertilización orgánica'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'25', production:'135', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-011',nombre:'Pineda Castillo, R.',monto:'L. 21,000',plazo:'6 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'El Naranjo', areaProd:'1.9 mz', geo:'14.92°N 88.32°W',carnet:'IHCAFE-2021-0115',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'44 qq / 3 ciclos',histIngresos:'1400 HNL / 3 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Cosecha de agua, Renovación de cafetales',
          practicasRecomendadas:'Injerto, Fertilización orgánica'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'22', production:'108', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb2-012',nombre:'Santos Mejía, E.',monto:'L. 28,000',plazo:'8 meses',destino:'Renovación',aval:'A',
        department:'Santa Bárbara', municipality:'San Nicolás', aldea:'El Sauce', areaProd:'2.8 mz', geo:'14.95°N 88.29°W',carnet:'IHCAFE-2018-0109',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'75 qq / 5 ciclos',histIngresos:'4000 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'7000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'high', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de cafetales, Aumentar la cobertura de sombra',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'29', production:'160', estimationDate:'2026-05-15'},
      ]},
  ]},
  {id:'tb3',tipo:'banco',testValue:'yes',fechaDesembolso:'2026-06-03',name:'Beneficio Rosales',region:'Santa Bárbara, Honduras',
    acopio:'1,800,000',productores:'198,000',nProd:9,paqueteFlexible:true,
    destinos:'Insumos, Cosecha, Renovación',areaProd:'17.5',volumenTotal:'454',
    plazoAcopio:'6',anios:12,volExport:'1,840',contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'600',mercados:'Alemania, Países Bajos',
    prod:[
      {cod:'HN-tb3-001',nombre:'Mendoza López, J.',monto:'L. 20,000',plazo:'6 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'La Cuchilla', areaProd:'1.6 mz', geo:'14.87°N 88.35°W',carnet:'IHCAFE-2021-0301',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'42 qq / 3 ciclos',histIngresos:'1300 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'2500 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua',
          practicasRecomendadas:'Injerto, Fertilización orgánica'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'22', production:'105', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-002',nombre:'Castro Mejía, R.',monto:'L. 24,000',plazo:'7 meses',destino:'Cosecha',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'El Carmen', areaProd:'2.1 mz', geo:'14.88°N 88.33°W',carnet:'IHCAFE-2020-0288',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'55 qq / 4 ciclos',histIngresos:'2100 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'high', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de cafetales, Cosecha de agua',
          practicasRecomendadas:'Uso de biochar en vivero, Conservación de suelos'},
        {id:'e2', risk:'medium', estimationDate:'2026-05-15'},
        {id:'e4', yield:'24', production:'120', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-003',nombre:'Hernández Cruz, M.',monto:'L. 18,000',plazo:'5 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'Los Pinos', areaProd:'1.3 mz', geo:'14.86°N 88.36°W',carnet:'IHCAFE-2022-0315',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'35 qq / 3 ciclos',histIngresos:'1000 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'2000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra',
          practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'20', production:'92', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-004',nombre:'Pineda Flores, A.',monto:'L. 27,000',plazo:'8 meses',destino:'Renovación',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'La Esperanza', areaProd:'2.7 mz', geo:'14.89°N 88.34°W',carnet:'IHCAFE-2019-0270',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'70 qq / 5 ciclos',histIngresos:'3800 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'6000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de árboles de sombra, Cosecha de agua',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'28', production:'150', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-005',nombre:'Mejía Santos, D.',monto:'L. 21,000',plazo:'6 meses',destino:'Cosecha',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'El Roble', areaProd:'1.8 mz', geo:'14.85°N 88.32°W',carnet:'IHCAFE-2021-0266',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'48 qq / 4 ciclos',histIngresos:'1700 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'unknown', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua',
          practicasRecomendadas:'Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'high', estimationDate:'2026-05-15'},
        {id:'e4', yield:'19', production:'88', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-006',nombre:'García Rivera, P.',monto:'L. 23,000',plazo:'7 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'El Paraíso', areaProd:'2.0 mz', geo:'14.90°N 88.31°W',carnet:'IHCAFE-2020-0255',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'52 qq / 4 ciclos',histIngresos:'2200 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'3500 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Cosecha de agua',
          practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'23', production:'115', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-007',nombre:'Ortega Mendoza, S.',monto:'L. 19,000',plazo:'5 meses',destino:'Insumos',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'Las Flores', areaProd:'1.5 mz', geo:'14.87°N 88.37°W',carnet:'IHCAFE-2018-0239',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'40 qq / 3 ciclos',histIngresos:'1200 HNL / 3 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra',
          practicasRecomendadas:'Injerto, Fertilización orgánica'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'21', production:'98', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-008',nombre:'Ramírez López, C.',monto:'L. 25,000',plazo:'7 meses',destino:'Renovación',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'El Cedral', areaProd:'2.4 mz', geo:'14.88°N 88.30°W',carnet:'IHCAFE-2019-0222',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'62 qq / 5 ciclos',histIngresos:'3000 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'5500 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'high', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de cafetales, Cosecha de agua',
          practicasRecomendadas:'Injerto, Uso de biochar en vivero, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'27', production:'145', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tb3-009',nombre:'Flores Aguilar, J.',monto:'L. 22,000',plazo:'6 meses',destino:'Cosecha',aval:'A',
        department:'Santa Bárbara', municipality:'La Arada', aldea:'La Cuchilla Centro', areaProd:'2.1 mz', geo:'14.86°N 88.33°W',carnet:'IHCAFE-2022-0208',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
        propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'50 qq / 4 ciclos',histIngresos:'1800 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua',
          practicasRecomendadas:'Injerto, Conservación de suelos, Fertilización orgánica'},
        {id:'e2', risk:'medium', estimationDate:'2026-05-15'},
        {id:'e4', yield:'24', production:'120', estimationDate:'2026-05-15'},
      ]},
    ]},
  ];

const LOANS_COOP_TEST=[
  {id:'tc1',tipo:'coop',testValue:'yes',fechaDesembolso:'2026-06-01',name:'Rosales Aguilar, Ramiro',region:'Santa Bárbara, Honduras',
    acopio:null,productores:'15,000',nProd:1,paqueteFlexible: false,
    destinos:'Cosecha, insumos',areaProd:'3.1',volumenTotal:'38',
    contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'38',
   prod:[
    {cod:'HN-tc1-001',nombre:'Rosales Aguilar, Ramiro',monto:'L. 15,000',plazo:'5 meses',destino:'Cosecha, insumos',aval:'A',
    department:'Santa Bárbara', municipality:'Arada', aldea:'El Palmo', areaProd:'3.1 mz', geo:'14.41°N 89.22°W',carnet:'IHCAFE-2020-0033',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
    propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'38 qq / 3 ciclos',histIngresos:'1300 HNL / 3 ciclos',otherIncome:'Sí', amountOtherIncome:'5000 HNL',
    esg:[
      {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim: 'high', calor: 'unknown', sequia: 'low', estimationDate:'2026-05-15',
        practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de árboles de sombra',
        practicasRecomendadas:'Injerto, Uso de biochar en vivero, Renovación de cafetales, Fertilización orgánica, Conservación de suelos'},
      {id:'e2', risk:'low', estimationDate:'2026-05-15'},
      {id:'e4', yield:'22', production:'110', estimationDate:'2026-05-15'},
    ]}]},
  {id:'tc2',tipo:'coop',testValue:'yes',fechaDesembolso:'2026-06-01',name:'Hernández López, María',region:'Santa Bárbara, Honduras',
    acopio:null,productores:'7,500',nProd:1,paqueteFlexible:false,
    destinos:'Insumos, Cosecha',areaProd:'2.7',volumenTotal:'52',
    contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'52',
  prod:[
    {cod:'HN-tc2-001',nombre:'Hernández López, María',monto:'L. 7,500',plazo:'6 meses',destino:'Insumos, Cosecha',aval:'A',
    department:'Santa Bárbara', municipality:'La Arada', aldea:'El Cedral', areaProd:'2.7 mz', geo:'14.45°N 89.18°W',carnet:'IHCAFE-2021-0048',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
    propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'52 qq / 4 ciclos',histIngresos:'2100 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'6000 HNL',
    esg:[
      {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
        practicasMuyRecomendadas:'Aumentar la cobertura de sombra',
        practicasRecomendadas:'Injerto, Uso de biochar en vivero, Fertilización orgánica, Conservación de suelos, Cosecha de agua'},
      {id:'e2', risk:'low', estimationDate:'2026-05-15'},
      {id:'e4', yield:'24', production:'120', estimationDate:'2026-05-15'},
    ]}]},
  {id:'tc3',tipo:'coop',testValue:'yes',fechaDesembolso:'2026-06-02',name:'Pérez Mendoza, José',region:'Santa Bárbara, Honduras',
    acopio:null,productores:'5,000',nProd:1,paqueteFlexible:false,
    destinos:'Cosecha, Renovación', areaProd:'3.0',volumenTotal:'47',
    contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'47',
  prod:[
    {cod:'HN-tc3-001',nombre:'Pérez Mendoza, J.',monto:'L. 5,000',plazo:'6 meses',destino:'Cosecha, Renovación',aval:'A',
    department:'Santa Bárbara', municipality:'La Arada', aldea:'La Cuchilla Centro', areaProd:'3.0 mz', geo:'14.47°N 89.20°W',carnet:'IHCAFE-2019-0061',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
    propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'47 qq / 4 ciclos',histIngresos:'1900 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'4500 HNL',
    esg:[
      {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
        practicasMuyRecomendadas:'Renovación de cafetales, Aumentar la cobertura de sombra, Cosecha de agua',
        practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos, Uso de biochar en vivero'},
      {id:'e2', risk:'high', estimationDate:'2026-05-15'},
      {id:'e4', yield:'23', production:'115', estimationDate:'2026-05-15'},
    ]}]},
];

const LOANS_GRUPO_TEST=[
  {id:'tg1',tipo:'grupo',testValue:'yes',fechaDesembolso:'2026-06-01',name:'Grupo de productores - La Arada',region:'Santa Bárbara, Honduras',
    acopio:null,productores:'58,500',nProd:3,paqueteFlexible:true,
    destinos:'Cosecha, Renovación', areaProd:'8.7',volumenTotal:'141',
    contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'141',
  prod:[
    {cod:'HN-tg1-001',nombre:'Pérez Mendoza, J.',monto:'L. 18,000',plazo:'6 meses',destino:'Cosecha, Renovación',aval:'A',
    department:'Santa Bárbara', municipality:'La Arada', aldea:'La Cuchilla Centro', areaProd:'3.0 mz', geo:'14.47°N 89.20°W',carnet:'IHCAFE-2019-0061',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
    propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'47 qq / 4 ciclos',histIngresos:'1900 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'4500 HNL',
    esg:[
      {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
        practicasMuyRecomendadas:'Renovación de cafetales, Aumentar la cobertura de sombra, Cosecha de agua',
        practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos, Uso de biochar en vivero'},
      {id:'e2', risk:'medium', estimationDate:'2026-05-15'},
      {id:'e4', yield:'23', production:'115', estimationDate:'2026-05-15'},
    ]},
    {cod:'HN-tg1-002',nombre:'Castro López, M.',monto:'L. 19,000',plazo:'5 meses',destino:'Cosecha',aval:'A',
    department:'Santa Bárbara', municipality:'La Arada', aldea:'El Cedral', areaProd:'2.5 mz', geo:'14.49°N 89.17°W',carnet:'IHCAFE-2020-0099',variedad:'Parainema',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
    propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'44 qq / 3 ciclos',histIngresos:'1700 HNL / 3 ciclos',otherIncome:'No', amountOtherIncome:'',
    esg:[
      {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
        practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua',
        practicasRecomendadas:'Fertilización orgánica, Conservación de suelos'},
      {id:'e2', risk:'low', estimationDate:'2026-05-15'},
      {id:'e4', yield:'21', production:'108', estimationDate:'2026-05-15'},
    ]},
    {cod:'HN-tg1-003',nombre:'Hernández Ruiz, S.',monto:'L. 21,500',plazo:'7 meses',destino:'Renovación',aval:'A',
    department:'Santa Bárbara', municipality:'La Arada', aldea:'Los Pinos', areaProd:'3.2 mz', geo:'14.46°N 89.21°W',carnet:'IHCAFE-2018-0127',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
    propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'50 qq / 4 ciclos',histIngresos:'2100 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'5000 HNL',
    esg:[
      {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
        practicasMuyRecomendadas:'Renovación de cafetales, Cosecha de agua',
        practicasRecomendadas:'Injerto, Uso de biochar en vivero, Conservación de suelos'},
      {id:'e2', risk:'low', estimationDate:'2026-05-15'},
      {id:'e4', yield:'25', production:'122', estimationDate:'2026-05-15'},
    ]},
  ]},
    {id:'tg2',tipo:'grupo',testValue:'yes',fechaDesembolso:'2026-06-02',name:'Cooperativa El Níspero Verde',region:'Lempira, Honduras',
      acopio:null,productores:'190,000',nProd:5,paqueteFlexible:false,
      destinos:'Cosecha, Insumos, Renovación',
      areaProd:'13.8',volumenTotal:'224',
      contrato:'Supremo Hamburg GmbH',smartContract:true,volContrato:'224',
    prod:[
      {cod:'HN-tg2-001',nombre:'Martínez Pineda, R.',monto:'L. 8,000',plazo:'6 meses',destino:'Cosecha, Insumos',aval:'A',
      department:'Lempira', municipality:'El Níspero', aldea:'San Juan', areaProd:'2.9 mz', geo:'14.56°N 88.62°W',carnet:'IHCAFE-2021-0410',variedad:'Lempira',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
      propertyDocument:'Sí', tenancyTipe:'Propiedad',histAcopio:'52 qq / 4 ciclos',histIngresos:'2200 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'5000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua, Renovación de cafetales',
          practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'24', production:'118', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tg2-002',nombre:'Hernández Cruz, M.',monto:'L. 18,000',plazo:'5 meses',destino:'Insumos, Cosecha',aval:'A',
      department:'Lempira', municipality:'El Níspero', aldea:'El Rosario', areaProd:'2.6 mz', geo:'14.58°N 88.60°W',carnet:'IHCAFE-2020-0388',variedad:'Catuaí rojo',riesgo:'Sin reporte negativo',confianza:'Aval otorgado',
      propertyDocument:'No', tenancyTipe:'Arriendo',histAcopio:'45 qq / 3 ciclos',histIngresos:'1800 HNL / 3 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'high', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de cafetales, Cosecha de agua',
          practicasRecomendadas:'Uso de biochar en vivero, Conservación de suelos'},
        {id:'e2', risk:'medium', estimationDate:'2026-05-15'},
        {id:'e4', yield:'22', production:'110', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tg2-003',nombre:'Flores Aguilar, J.',monto:'L. 15,000',plazo:'7 meses',destino:'Renovación',
      aval:'A', department:'Lempira', municipality:'El Níspero', aldea:'La Laguna', areaProd:'2.9 mz',
      geo:'14.57°N 88.61°W',carnet:'IHCAFE-2019-0422',variedad:'Parainema',riesgo:'Sin reporte negativo',
      confianza:'Aval otorgado', propertyDocument:'Sí', tenancyTipe:'Propiedad',
      histAcopio:'42 qq / 4 ciclos',histIngresos:'2000 HNL / 4 ciclos',otherIncome:'Sí', amountOtherIncome:'4000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'medium', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Renovación de cafetales, Aumentar la cobertura de sombra',
          practicasRecomendadas:'Injerto, Fertilización orgánica, Conservación de suelos, Uso de biochar en vivero'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'26', production:'130', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tg2-004',nombre:'Castro Mendoza, L.',monto:'L. 20,000',plazo:'8 meses',destino:'Renovación',
      aval:'A', department:'Lempira', municipality:'El Níspero', aldea:'El Paraíso', areaProd:'3.4 mz',
      geo:'14.59°N 88.63°W',carnet:'IHCAFE-2018-0441',variedad:'Lempira',riesgo:'Sin reporte negativo',
      confianza:'Aval otorgado', propertyDocument:'Sí', tenancyTipe:'Propiedad',
      histAcopio:'60 qq / 5 ciclos',histIngresos:'2800 HNL / 5 ciclos',otherIncome:'Sí', amountOtherIncome:'6000 HNL',
      esg:[
        {id:'e1', aptitudClimActual:'medium', aptitudClimFutura:'high', gradienteClim:'high', calor:'medium', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Cosecha de agua, Renovación de cafetales, Aumentar la cobertura de sombra',
          practicasRecomendadas:'Injerto, Conservación de suelos, Fertilización orgánica'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'28', production:'145', estimationDate:'2026-05-15'},
      ]},
      {cod:'HN-tg2-005',nombre:'Ramírez López, S.',monto:'L. 11,000',plazo:'6 meses',destino:'Cosecha',
      aval:'A', department:'Lempira', municipality:'El Níspero', aldea:'Los Pinos',
      areaProd:'2.0 mz', geo:'14.55°N 88.64°W',carnet:'IHCAFE-2022-0405',variedad:'Catuaí rojo',
      riesgo:'Sin reporte negativo',confianza:'Aval otorgado', propertyDocument:'No', tenancyTipe:'Arriendo',
      histAcopio:'50 qq / 4 ciclos',histIngresos:'2100 HNL / 4 ciclos',otherIncome:'No', amountOtherIncome:'',
      esg:[
        {id:'e1', aptitudClimActual:'low', aptitudClimFutura:'medium', gradienteClim:'high', calor:'low', sequia:'medium', estimationDate:'2026-05-15',
          practicasMuyRecomendadas:'Aumentar la cobertura de sombra, Cosecha de agua',
          practicasRecomendadas:'Fertilización orgánica, Conservación de suelos'},
        {id:'e2', risk:'low', estimationDate:'2026-05-15'},
        {id:'e4', yield:'23', production:'112', estimationDate:'2026-05-15'},
      ]},
    ]},
  ];


// ── Credits list: DCE ──────────────────────────────────────────────────────
const LOANS_BANCO=[
  {id:'b2',grupoId:1,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'20,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
  {id:'b4',grupoId:2,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'100,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
  {id:'b6',grupoId:3,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'20,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
  {id:'b8',grupoId:4,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'100,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
  {id:'b12',grupoId:5,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'20,000',nProd:'5',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
  {id:'b16',grupoId:7,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'20,000',nProd:'10',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
  {id:'b18',grupoId:8,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'100,000',nProd:'10',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
  {id:'b20',grupoId:9,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'20,000',nProd:'5',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
  {id:'b22',grupoId:10,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:'1,000,000',productores:'100,000',nProd:'5',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
  {id:'b21',grupoId:1,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-23',name:'',acopio:'1,000,000',productores:'100,000',nProd:'10',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
  {id:'b26',grupoId:2,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-23',name:'',acopio:'1,000,000',productores:'100,000',nProd:'10',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
  {id:'b30',grupoId:3,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-10',name:'',acopio:'1,000,000',productores:'20,000',nProd:'5',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
  {id:'b32',grupoId:4,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-17',name:'',acopio:'1,000,000',productores:'100,000',nProd:'5',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
  {id:'b34',grupoId:5,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-10',name:'',acopio:'1,000,000',productores:'20,000',nProd:'10',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
  {id:'b36',grupoId:6,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-29',name:'',acopio:'1,000,000',productores:'100,000',nProd:'10',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
  {id:'b38',grupoId:7,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-18',name:'',acopio:'1,000,000',productores:'20,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
  {id:'b40',grupoId:8,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-19',name:'',acopio:'1,000,000',productores:'100,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
  {id:'b42',grupoId:9,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-14',name:'',acopio:'1,000,000',productores:'20,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
  {id:'b44',grupoId:10,tipo:'banco',testValue:'no',fechaDesembolso:'2026-06-28',name:'',acopio:'1,000,000',productores:'100,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
];

const LOANS_COOP=[
{id:'c9',grupoId:1,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'c10',grupoId:2,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'c27',grupoId:3,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
{id:'c28',grupoId:4,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
{id:'c45',grupoId:5,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'c46',grupoId:6,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'c63',grupoId:7,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:false,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
{id:'c64',grupoId:8,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:false,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
{id:'c81',grupoId:9,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:false,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'c82',grupoId:10,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:false,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'c99',grupoId:1,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-24',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:false,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'c100',grupoId:2,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-18',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:false,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'c117',grupoId:3,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-19',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:false,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
{id:'c118',grupoId:4,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-27',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:false,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
{id:'c135',grupoId:5,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-22',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:false,whisp:false,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'c136',grupoId:6,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-18',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:false,whisp:false,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'c153',grupoId:7,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-22',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:false,priceTools:null,continue:false,priceTotal:'50',},
{id:'c154',grupoId:8,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-16',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:false,priceTools:null,continue:false,priceTotal:'50',},
{id:'c171',grupoId:9,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-24',name:'',acopio:null,productores:'20,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:false,priceTools:'50',continue:false,priceTotal:'50',},
{id:'c172',grupoId:10,tipo:'coop',testValue:'no',fechaDesembolso:'2026-06-29',name:'',acopio:null,productores:'100,000',nProd:'1',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:false,priceTools:'50',continue:false,priceTotal:'50',},
];

const LOANS_GRUPO=[
{id:'g1',grupoId:1,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g3',grupoId:2,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g5',grupoId:3,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g7',grupoId:4,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g11',grupoId:5,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'5',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g13',grupoId:6,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'5',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g15',grupoId:7,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'10',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g17',grupoId:8,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'10',paqueteFlexible:false,fundamentales:true,priceFundamentales:'50',aclimatar:true,whisp:true,croppie:true,priceTools:null,continue:true,priceTotal:'50',},
{id:'g19',grupoId:9,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'20,000',nProd:'5',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
{id:'g21',grupoId:10,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-09',name:'',acopio:null,productores:'100,000',nProd:'5',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:true,priceTotal:'50',},
{id:'g23',grupoId:1,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-26',name:'',acopio:null,productores:'20,000',nProd:'10',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'g25',grupoId:2,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-27',name:'',acopio:null,productores:'100,000',nProd:'10',paqueteFlexible:true,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'g29',grupoId:3,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-22',name:'',acopio:null,productores:'20,000',nProd:'5',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'g31',grupoId:4,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-29',name:'',acopio:null,productores:'100,000',nProd:'5',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'g33',grupoId:5,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-19',name:'',acopio:null,productores:'20,000',nProd:'10',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'g35',grupoId:6,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-15',name:'',acopio:null,productores:'100,000',nProd:'10',paqueteFlexible:false,fundamentales:false,priceFundamentales:null,aclimatar:true,whisp:true,croppie:true,priceTools:'50',continue:false,priceTotal:'50',},
{id:'g37',grupoId:7,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-16',name:'',acopio:null,productores:'20,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
{id:'g39',grupoId:8,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-10',name:'',acopio:null,productores:'100,000',nProd:'5',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
{id:'g41',grupoId:9,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-13',name:'',acopio:null,productores:'20,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
{id:'g43',grupoId:10,tipo:'grupo',testValue:'no',fechaDesembolso:'2026-06-25',name:'',acopio:null,productores:'100,000',nProd:'10',paqueteFlexible:true,fundamentales:true,priceFundamentales:'50',aclimatar:false,whisp:true,croppie:true,priceTools:null,continue:false,priceTotal:'50',},
];